### ISSUE TITLE
Add tests to modules

### ISSUE THREAD

**Issue by de-sh** [vyuham/rtrcrs#4]
There seems to be some unforeseen bugs in the code, that might have crept in through while converting from CPP to rust-lang.

The modules that need to covered are:
- `vector`
- `color`
- `ray`

### Test Code Format
- For modules:
```rust
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn functionality_test() {
        assert_eq!(functionality(some_input), expected_output);
    }
}
```

**Comment by 123vivekr** [comment]
There seems to be an issue with the floating point imprecision.
See [link](https://stackoverflow.com/questions/50361151/how-to-deal-with-inexact-floating-point-arithmetic-results-in-rust).

**Comment by de-sh** [comment]
Can you try using `{0:..5}` within `color.rs`?

**Comment by de-sh** [comment]
We have to find out how much this issue leeches into and contributes to our over-all problem.
